-- CreateTable
CREATE TABLE `Property` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(191) NOT NULL,
    `location` VARCHAR(191) NOT NULL,
    `price` DECIMAL(15, 2) NOT NULL,
    `bedrooms` INTEGER NOT NULL,
    `bathrooms` INTEGER NOT NULL,
    `size` INTEGER NOT NULL,
    `description` TEXT NULL,
    `community` VARCHAR(191) NOT NULL,
    `balcony` BOOLEAN NOT NULL DEFAULT false,
    `type` VARCHAR(191) NOT NULL,
    `purpose` VARCHAR(191) NOT NULL,
    `referenceNo` VARCHAR(191) NOT NULL,
    `completion` VARCHAR(191) NOT NULL,
    `furnishing` VARCHAR(191) NOT NULL,
    `addedOn` DATETIME(3) NOT NULL,
    `handoverDate` VARCHAR(191) NULL,
    `developer` VARCHAR(191) NULL,
    `ownership` VARCHAR(191) NULL,
    `builtUpArea` INTEGER NULL,
    `usage` VARCHAR(191) NULL,
    `balconySize` INTEGER NULL,
    `parkingAvailability` BOOLEAN NOT NULL DEFAULT false,
    `buildingName` VARCHAR(191) NULL,
    `totalFloors` INTEGER NULL,
    `swimmingPools` INTEGER NULL,
    `totalParkingSpaces` INTEGER NULL,
    `totalBuildingArea` DECIMAL(15, 2) NULL,
    `elevators` INTEGER NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `Property_referenceNo_key`(`referenceNo`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
